/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digitalclock;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author Juan Carlos Vilarrubia
 */
public class AlarmPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlarmPanel
     */
    public AlarmPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDateTime = new javax.swing.JLabel();
        jSpinnerDateTime = new javax.swing.JSpinner();
        jCheckBoxActive = new javax.swing.JCheckBox();
        jLabelMessage = new javax.swing.JLabel();
        jTextFieldMessage = new javax.swing.JTextField();

        jLabelDateTime.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelDateTime.setText("Fije la fecha y la hora de la alarma");
        jLabelDateTime.setToolTipText("Etiqueta referente a la fecha y hora");

        jSpinnerDateTime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jSpinnerDateTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MONTH));
        jSpinnerDateTime.setToolTipText("Elija la fecha y la hora de la alarma");

        jCheckBoxActive.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCheckBoxActive.setText("Activar");
        jCheckBoxActive.setToolTipText("Seleccione si la alarma está activa");
        jCheckBoxActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActiveActionPerformed(evt);
            }
        });

        jLabelMessage.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelMessage.setText("Mensaje de la alarma");
        jLabelMessage.setToolTipText("Etiqueta del campo de texto");

        jTextFieldMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldMessage.setToolTipText("Ingrese el mensaje a mostrar cuando se lance la alarma");
        jTextFieldMessage.setAlignmentY(0.0F);
        jTextFieldMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMessage)
                    .addComponent(jLabelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxActive))
                    .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelDateTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxActiveActionPerformed

    private void jTextFieldMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMessageActionPerformed

    public Alarm getSelectedValue() {

        Date date = (Date) jSpinnerDateTime.getValue();
        LocalDateTime datetime = LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
        
        boolean active = jCheckBoxActive.isSelected();
        String message = jTextFieldMessage.getText();

        if (date != null) {
            return new Alarm(datetime, active, message);
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxActive;
    private javax.swing.JLabel jLabelDateTime;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JSpinner jSpinnerDateTime;
    private javax.swing.JTextField jTextFieldMessage;
    // End of variables declaration//GEN-END:variables
}
