/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package digitalclock;

/**
 *
 * @author Juan Carlos Vilarrubia
 */
public class AlarmPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlarmPanel
     */
    public AlarmPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAlarmTime = new javax.swing.JLabel();
        jSpinnerHour = new javax.swing.JSpinner();
        jCheckBoxActive = new javax.swing.JCheckBox();
        jLabelMessage = new javax.swing.JLabel();
        jTextFieldMessage = new javax.swing.JTextField();
        jLabelHour = new javax.swing.JLabel();
        jLabelMinutes = new javax.swing.JLabel();
        jSpinnerMinutes = new javax.swing.JSpinner();

        jLabelAlarmTime.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelAlarmTime.setText("Fije la hora de la alarma");
        jLabelAlarmTime.setToolTipText("Permite fijar la hora de la alarma y si esta activa o no");

        jSpinnerHour.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jSpinnerHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        jSpinnerHour.setToolTipText("Permite fijar la hora de la alarma y si esta activa o no");

        jCheckBoxActive.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCheckBoxActive.setText("Activar");
        jCheckBoxActive.setToolTipText("Seleccione si la alarma está activa");
        jCheckBoxActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActiveActionPerformed(evt);
            }
        });

        jLabelMessage.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelMessage.setText("Mensaje de alarma");
        jLabelMessage.setToolTipText("Etiqueta del campo de texto");

        jTextFieldMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldMessage.setToolTipText("Ingrese el mensaje a mostrar cuando se lance la alarma");
        jTextFieldMessage.setAlignmentY(0.0F);
        jTextFieldMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMessageActionPerformed(evt);
            }
        });

        jLabelHour.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelHour.setText("Hora");
        jLabelHour.setToolTipText("Hora de la alarma");

        jLabelMinutes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelMinutes.setText("Minutos");
        jLabelMinutes.setToolTipText("Minutos de la alarma");

        jSpinnerMinutes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jSpinnerMinutes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelAlarmTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelMessage)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabelHour)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinnerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelMinutes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinnerMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBoxActive, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelAlarmTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHour)
                    .addComponent(jSpinnerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMinutes)
                    .addComponent(jSpinnerMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxActive))
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jSpinnerHour.getAccessibleContext().setAccessibleDescription("Elija la hora de la alarma");
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxActiveActionPerformed

    private void jTextFieldMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMessageActionPerformed

    public Alarm getSelectedValue() {

        int hour = (int) jSpinnerHour.getValue();
        int minute = (int) jSpinnerMinutes.getValue();
        boolean active = jCheckBoxActive.isSelected();
        String message = jTextFieldMessage.getText();

        return new Alarm(hour, minute, active, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxActive;
    private javax.swing.JLabel jLabelAlarmTime;
    private javax.swing.JLabel jLabelHour;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelMinutes;
    private javax.swing.JSpinner jSpinnerHour;
    private javax.swing.JSpinner jSpinnerMinutes;
    private javax.swing.JTextField jTextFieldMessage;
    // End of variables declaration//GEN-END:variables
}
